spring:
  application:
    name: spring-cloud-api-gateway-zuul
  zipkin:
    # 分布式服务调用链路跟踪。zipkin 默认地址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8009

zuul:
  routes:
    # 访问 http://localhost:8009/it/spring-cloud，请求重定向
    baidu:
      path: /it/**
      url: http://www.ityouknow.com/
    # 访问 http://localhost:8009/helloZ/helloZuul?name=yaojin，请求重定向到注册中心端口URL映射。
    # 其中，path的helloZ为一级映射路径，helloZuul为接口@RequestMapping注解中的映射地址
    hello:
      path: /helloZ/**
      # 指定转发到单一的服务ip与端口
      url: http://localhost:9002/
      # 配置多个服务时，通过配置serviceId调用服务集群中的接口功能
      # serviceId: spring-cloud-producer
  # 开启zuul retry
  retryable: true
  # 使用线程池做隔离，默认是信号量SEMAPHORE（信号量）
  ribbon-isolation-strategy: thread
  thread-pool:
    # 线程名称前缀
    thread-pool-key-prefix: zuulgw
    # 为不同的路由使用不同的线程池
    use-separate-thread-pools: true

# 要支持重试的微服务的配置
# 此时请求的链接为：http://localhost:8009/spring-cloud-producer/zuulRetry?name=yaojin
spring-cloud-producer:
  ribbon:
    #ribbon请求连接的超时时间
    ConnectTimeout: 1000
    #请求处理的超时时间
    ReadTimeout: 1000
    #对所有请求操作都进行重试。设置为false，表示只会对get请求进行重试
    OkToRetryOnAllOperations: true
    #对服务实例的重试次数（除去首次访问外）。默认值为0，如果不设置，则只会有首次访问，不会有重试
    MaxAutoRetries: 3
    #切换到另一个实例的次数。默认值为1，如果不设置，会有一次切换
    MaxAutoRetriesNextServer: 0

#
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

  # 服务提供者配置
  client:
    # 服务注册中心地址
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

