spring:
  application:
    name: spring-cloud-producer
  zipkin:
    # 分布式服务调用链路跟踪。zipkin 默认地址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 9012

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
