spring:
  application:
    name: spring-cloud-consumer-hystrix
  main:
    allow-bean-definition-overriding: true

server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

feign:
  hystrix:
    # 打开熔断器
    enabled: true
